### ISSUE TITLE
Add some documentation and screenshots to the readme file

### ISSUE THREAD

**Issue by Call-Me-Dave** [VaZaR00/FTB-gramps-import-addon#2]
Attempt at documentation.

<s>Include a link to the download file for FTB</s> and mention if it works with a minimum version of the FTB program?

Announcement from developer on Gramps Forum:

---

> [MyHeritage FTB to Gramps data transfer](https://gramps.discourse.group/t/myheritage-ftb-to-gramps-data-transfer/6516)
> 
> I have created my first addon for transfering data from [MyHeritage Family Tree Builder](https://www.myheritage.com/help-center?a=Is-Family-Tree-Builder-free---id--Ee02e4IdQAuJFZ-BRKCcFw) to Gramps. Its just fully imports data from FTB using its local SQLite DB.
> 
> I hope it will be useful for someone.
> 

--

Some screenshots

![2024-11-30 07_54_27-Family Tree 1 - Dashboard - Gramps](https://github.com/user-attachments/assets/3c7f1534-44da-48da-a64d-dcfb7d1db4b5)

![2024-11-30 07_54_47-Family Tree 1 - Dashboard - Gramps](https://github.com/user-attachments/assets/184ffa80-b34e-4006-b101-7eb855a8c660)

![2024-11-30 07_55_16-Family Tree 1 - Dashboard - Gramps](https://github.com/user-attachments/assets/b6907363-5235-4e13-9d4a-8d3917150a0b)

![2024-11-30 07_55_29-FTB Project path](https://github.com/user-attachments/assets/3919f274-e115-4e7e-8815-66198cce8929)
![2024-11-30 08_08_06-MyHeritage Family Tree Builder 8 0 Setup](https://github.com/user-attachments/assets/75c2e3ec-decc-4eb8-8f56-67aea63b4f3c)
![2024-11-30 08_08_23-MyHeritage Family Tree Builder 8 0 Setup](https://github.com/user-attachments/assets/6b70102e-dcda-4d57-8318-c6780ee379ce)

![2024-11-30 08_10_39-Mozilla Firefox](https://github.com/user-attachments/assets/46115f01-d7c8-4d8a-b4be-8d71ee943347)
![2024-11-30 08_10_13-Mozilla Firefox](https://github.com/user-attachments/assets/ab293fe0-1404-4048-a1bc-db91805f4b8b)

**Comment by ghost** [comment]
Thanks for the addon 😊

<s>I was going to continue to document this but this is as far as I can go as I don't want an account with this company ([based on past interactions!](https://www.reddit.com/r/Genealogy/comments/xz0lkh/why_does_everybody_hate_myheritage_so_much/))  Hopefully some body else will continue!</s>  Will use the sample ftb file  ( 95 person tree for American president John Fitzgerald Kennedy.)

Questions:
*Does the addon really sync future updates or is it only one way from FTB to Gramps?  
*Do you recommend that the sync only be done into an empty family tree?

For anyone wanting to use FTB 
* [How to Use Family Tree Builder for Genealogy](https://education.myheritage.com/article/how-to-use-family-tree-builder-for-genealogy/)  - You need to have a MyHeritage account to use Family Tree Builder. When you first run the program, you’ll be prompted to sign up for a MyHeritage account or log in to your existing account.

* [Can I choose not to sync my Family Tree Builder tree with my site?](https://www.myheritage.com/help-center?a=Can-I-choose-not-to-sync-my-Family-Tree-Builder-tree-with-my-site---id--CCAqSgaZT_Kt2nSbgl76Xg) - To do so, you should stop the ‘**Automatic sync’** in Family Tree Builder as described.

* Direct download link [https://myheritage.com/FTB](https://myheritage.com/FTB)

**Comment by VaZaR00** [comment]
Thanks for help!
Answering questions:
1)*Does the addon really sync future updates or is it only one way from FTB to Gramps?*
The name sync was choosen at start of work, as i planned to make it sync, but later after some struggling i ended up just making import, maybe later (cant promise) i will make it really sync, after this experience, i have some ideas how to make it...
2)*Do you recommend that the sync only be done into an empty family tree?*
Well at first import: yes. But later you "update" your tree just reimporting it all. I wrote in readme how it works.

**Comment by ghost** [comment]
Your welcome.

> The name sync was choosen at start of work, as i planned to make it sync, but later after some struggling i ended up just making import, maybe later (cant promise) i will make it really sync, after this experience, i have some ideas how to make it...

Ok maybe rename the addon to just **FTB-Importer**  for now to reflect that?


FYI worked out the FTB install directory has sample files in:

> **C:\Program Files (x86)\MyHeritage\Data\Sample\Database**

I'm checking to see if I can get the addon to find the file directly to import or is that not possible?

**Comment by ghost** [comment]
I managed to get the addon working by just coping the sample ( 95 person tree for American president John Fitzgerald Kennedy.) database to the folder:

> C:\Documents\Documents\MyHeritage

![2024-11-30 09_14_39-Progress](https://github.com/user-attachments/assets/b89af207-5c36-4733-b833-4667574bad63)

![2024-11-30 09_15_22-](https://github.com/user-attachments/assets/68c647eb-5fd6-4f9e-8f8e-a3302500815b)

![2024-11-30 09_15_32-Completion](https://github.com/user-attachments/assets/2b3d6d5c-3860-453d-a231-3ddc3ca14549)

End result for the Sample  95 person tree for American president John Fitzgerald Kennedy.
![2024-11-30 09_22_37-Family Tree 1 - People Tree View - Gramps](https://github.com/user-attachments/assets/dc712256-25c3-467c-913c-19e1acdac415)

**Comment by VaZaR00** [comment]
Ok, i'll rename it.
You have to choose folder of your tree project which is located in Documents/MyHeritage/*tree project*. I wrote in readme how to get the folder location

**Comment by VaZaR00** [comment]
Updated readme further
