### ISSUE TITLE
Please add reassuring note at top of README.md 

### ISSUE THREAD

**Issue by emyoulation** [VaZaR00/FTB-gramps-import-addon#4]
Thank you for sharing this new addon!

Could you add an explicit note at the top of the README.md file that says whether the FTB database will be changed during the Tool? (It will probably change the "last accessed date" but nothing else?) Does it read a local file or just a cloud file?

And when the Sync Tool can change/overwrite existing records in the Gramps Tree.   

Haven't explored yet because I have to create a FTB file first.

Looking forward to exploring.
Thanks again.

**Comment by VaZaR00** [comment]
Okay i'll add note. Its not sync yet and cant promise when it will be. It supposed to be sync at start of development but later i just made import but classnames stayed same. It doesn't overwrite FTB database. It reads local SQLite file.

**Comment by emyoulation** [comment]
Thank you!

Copied your updated README.md content to Discourse and made it a "wiki" posting that anyone can revise.

**Comment by VaZaR00** [comment]
Cool. Thanks
